export const products = [
  {
    id: 1,
    name: 'Rice',
    category: 'Basic Foods',
    price: 5.99,
    stock: 120,
    code: 'BF001',
  },
  {
    id: 2,
    name: 'Black Beans',
    category: 'Basic Foods',
    price: 7.49,
    stock: 85,
    code: 'BF002',
  },
  {
    id: 3,
    name: 'Olive Oil',
    category: 'Oils and Spices',
    price: 19.99,
    stock: 60,
    code: 'OS001',
  },
  {
    id: 4,
    name: 'Wheat Flour',
    category: 'Bakery',
    price: 4.89,
    stock: 100,
    code: 'BK001',
  },
  {
    id: 5,
    name: 'Milk',
    category: 'Dairy',
    price: 4.29,
    stock: 200,
    code: 'DA001',
  },
  {
    id: 6,
    name: 'Chocolate Cookies',
    category: 'Snacks',
    price: 2.99,
    stock: 150,
    code: 'SN001',
  },
  {
    id: 7,
    name: 'Soda Cola',
    category: 'Beverages',
    price: 6.49,
    stock: 90,
    code: 'BE001',
  },
  {
    id: 8,
    name: 'Chicken',
    category: 'Meats',
    price: 15.99,
    stock: 40,
    code: 'ME001',
  },
  {
    id: 9,
    name: 'Tomato',
    category: 'Fruits and Vegetables',
    price: 8.99,
    stock: 110,
    code: 'FV001',
  },
  {
    id: 10,
    name: 'Toilet Paper',
    category: 'Hygiene',
    price: 12.99,
    stock: 75,
    code: 'HY001',
  },
];
