export const products = [
  { name: 'Rice', category: 'Basic Foods' },
  { name: 'Beans', category: 'Basic Foods' },
  { name: 'Pasta', category: 'Basic Foods' },
  { name: 'Salt', category: 'Oils and Spices' },
  { name: 'Pepper', category: 'Oils and Spices' },
  { name: 'Oil', category: 'Oils and Spices' },
  { name: 'Bread', category: 'Bakery' },
  { name: 'Bread flour', category: 'Bakery' },
  { name: 'Sugar', category: 'Bakery' },
  { name: 'Butter', category: 'Bakery' },
  { name: 'Milk', category: 'Dairy' },
  { name: 'Cheese', category: 'Dairy' },
  { name: 'Yogurt', category: 'Dairy' },
  { name: 'Chicken', category: 'Meat' },
  { name: 'Beef', category: 'Meat' },
  { name: 'Fish', category: 'Meat' },
  { name: 'Eggs', category: 'Dairy' },
  { name: 'Apples', category: 'Fruits and Vegetables' },
  { name: 'Bananas', category: 'Fruits and Vegetables' },
  { name: 'Oranges', category: 'Fruits and Vegetables' },
  { name: 'Carrots', category: 'Fruits and Vegetables' },
  { name: 'Potatoes', category: 'Fruits and Vegetables' },
  { name: 'Lettuce', category: 'Fruits and Vegetables' },
  { name: 'Tomatoes', category: 'Fruits and Vegetables' },
  { name: 'Coffee', category: 'Beverages' },
  { name: 'Tea', category: 'Beverages' },
  { name: 'Juice', category: 'Beverages' },
  { name: 'Cereal', category: 'Breakfast' },
  { name: 'Honey', category: 'Breakfast' },
  { name: 'Jam', category: 'Breakfast' },
  { name: 'Chips', category: 'Snacks' },
  { name: 'Chocolate', category: 'Snacks' },
  { name: 'Cookies', category: 'Snacks' },
  { name: 'Flour', category: 'Bakery' },
  { name: 'Yeast', category: 'Bakery' },
  { name: 'Vinegar', category: 'Oils and Spices' },
  { name: 'Garlic', category: 'Oils and Spices' },
  { name: 'Onions', category: 'Fruits and Vegetables' },
];
export type Product = {
  name: string;
  category: string;
};

export const categories = [
  { id: 1, name: 'Basic Foods' },
  { id: 2, name: 'Oils and Spices' },
  { id: 3, name: 'Bakery' },
  { id: 4, name: 'Dairy' },
  { id: 5, name: 'Snacks' },
  { id: 6, name: 'Beverages' },
  { id: 7, name: 'Meats' },
  { id: 8, name: 'Fruits and Vegetables' },
  { id: 9, name: 'Hygiene' },
];
