export const products = [
  { name: 'Rice', category: 'Basic Foods' },
  { name: 'Beans', category: 'Basic Foods' },
  { name: 'Pasta', category: 'Basic Foods' },
  { name: 'Salt', category: 'Oils and Spices' },
  { name: 'Pepper', category: 'Oils and Spices' },
  { name: 'Oil', category: 'Oils and Spices' },
  { name: 'Bread', category: 'Bakery' },
  { name: 'Bread flour', category: 'Bakery' },
  { name: 'Sugar', category: 'Bakery' },
  { name: 'Butter', category: 'Bakery' },
  { name: 'Milk', category: 'Dairy' },
  { name: 'Cheese', category: 'Dairy' },
  { name: 'Yogurt', category: 'Dairy' },
  { name: 'Eggs', category: 'Dairy' },
  { name: 'Chicken', category: 'Meat' },
  { name: 'Beef', category: 'Meat' },
  { name: 'Fish', category: 'Meat' },
  { name: 'Turkey', category: 'Meat' },
  { name: 'Sausage', category: 'Meat' },
  { name: 'Pork', category: 'Meat' },
  { name: 'Lamb', category: 'Meat' },
  { name: 'Apples', category: 'Fruits and Vegetables' },
  { name: 'Bananas', category: 'Fruits and Vegetables' },
  { name: 'Oranges', category: 'Fruits and Vegetables' },
  { name: 'Carrots', category: 'Fruits and Vegetables' },
  { name: 'Potatoes', category: 'Fruits and Vegetables' },
  { name: 'Lettuce', category: 'Fruits and Vegetables' },
  { name: 'Tomatoes', category: 'Fruits and Vegetables' },
  { name: 'Onions', category: 'Fruits and Vegetables' },
  { name: 'Garlic', category: 'Oils and Spices' },
  { name: 'Spinach', category: 'Fruits and Vegetables' },
  { name: 'Cucumber', category: 'Fruits and Vegetables' },
  { name: 'Peppers', category: 'Fruits and Vegetables' },
  { name: 'Cabbage', category: 'Fruits and Vegetables' },
  { name: 'Pineapple', category: 'Fruits and Vegetables' },
  { name: 'Mango', category: 'Fruits and Vegetables' },
  { name: 'Watermelon', category: 'Fruits and Vegetables' },
  { name: 'Blueberries', category: 'Fruits and Vegetables' },
  { name: 'Strawberries', category: 'Fruits and Vegetables' },
  { name: 'Cherries', category: 'Fruits and Vegetables' },
  { name: 'Raspberries', category: 'Fruits and Vegetables' },
  { name: 'Grapes', category: 'Fruits and Vegetables' },
  { name: 'Avocados', category: 'Fruits and Vegetables' },
  { name: 'Lemon', category: 'Fruits and Vegetables' },
  { name: 'Kiwi', category: 'Fruits and Vegetables' },
  { name: 'Cantaloupe', category: 'Fruits and Vegetables' },
  { name: 'Coffee', category: 'Beverages' },
  { name: 'Tea', category: 'Beverages' },
  { name: 'Juice', category: 'Beverages' },
  { name: 'Soda', category: 'Beverages' },
  { name: 'Wine', category: 'Beverages' },
  { name: 'Beer', category: 'Beverages' },
  { name: 'Sparkling Water', category: 'Beverages' },
  { name: 'Coconut Water', category: 'Beverages' },
  { name: 'Cereal', category: 'Breakfast' },
  { name: 'Honey', category: 'Breakfast' },
  { name: 'Jam', category: 'Breakfast' },
  { name: 'Granola', category: 'Breakfast' },
  { name: 'Oats', category: 'Breakfast' },
  { name: 'Pancake Mix', category: 'Breakfast' },
  { name: 'Maple Syrup', category: 'Breakfast' },
  { name: 'Muesli', category: 'Breakfast' },
  { name: 'Chia Seeds', category: 'Breakfast' },
  { name: 'Almond Butter', category: 'Snacks' },
  { name: 'Peanut Butter', category: 'Snacks' },
  { name: 'Chips', category: 'Snacks' },
  { name: 'Chocolate', category: 'Snacks' },
  { name: 'Cookies', category: 'Snacks' },
  { name: 'Pretzels', category: 'Snacks' },
  { name: 'Popcorn', category: 'Snacks' },
  { name: 'Almonds', category: 'Snacks' },
  { name: 'Cashews', category: 'Snacks' },
  { name: 'Walnuts', category: 'Snacks' },
  { name: 'Pistachios', category: 'Snacks' },
  { name: 'Trail Mix', category: 'Snacks' },
  { name: 'Rice Cakes', category: 'Snacks' },
  { name: 'Granola Bars', category: 'Snacks' },
  { name: 'Ice Cream', category: 'Desserts' },
  { name: 'Cake', category: 'Desserts' },
  { name: 'Brownies', category: 'Desserts' },
  { name: 'Pudding', category: 'Desserts' },
  { name: 'Pie', category: 'Desserts' },
  { name: 'Flour', category: 'Bakery' },
  { name: 'Yeast', category: 'Bakery' },
  { name: 'Vinegar', category: 'Oils and Spices' },
  { name: 'Soy Sauce', category: 'Oils and Spices' },
  { name: 'Mustard', category: 'Oils and Spices' },
  { name: 'Ketchup', category: 'Oils and Spices' },
  { name: 'Mayonnaise', category: 'Oils and Spices' },
  { name: 'Coconut Oil', category: 'Oils and Spices' },
  { name: 'Olive Oil', category: 'Oils and Spices' },
  { name: 'Cinnamon', category: 'Oils and Spices' },
  { name: 'Nutmeg', category: 'Oils and Spices' },
  { name: 'Cloves', category: 'Oils and Spices' },
  { name: 'Rosemary', category: 'Oils and Spices' },
  { name: 'Thyme', category: 'Oils and Spices' },
  { name: 'Basil', category: 'Oils and Spices' },
  { name: 'Oregano', category: 'Oils and Spices' },
  { name: 'Parsley', category: 'Oils and Spices' },
  { name: 'Chili Powder', category: 'Oils and Spices' },
  { name: 'Paprika', category: 'Oils and Spices' },
  { name: 'Curry Powder', category: 'Oils and Spices' },
  { name: 'Saffron', category: 'Oils and Spices' },
  { name: 'Taco Seasoning', category: 'Oils and Spices' },
  { name: 'Hot Sauce', category: 'Oils and Spices' },
  { name: 'Barbecue Sauce', category: 'Oils and Spices' },
  { name: 'Coconut Milk', category: 'Oils and Spices' },
  { name: 'Tomato Sauce', category: 'Oils and Spices' },
  { name: 'Mustard Seeds', category: 'Oils and Spices' },
  { name: 'Fenugreek', category: 'Oils and Spices' },
  { name: 'Cumin', category: 'Oils and Spices' },
  { name: 'Tumeric', category: 'Oils and Spices' },
  { name: 'Lemon Juice', category: 'Oils and Spices' },
  { name: 'Lime Juice', category: 'Oils and Spices' },
  { name: 'Apple Cider Vinegar', category: 'Oils and Spices' },
  { name: 'Lemon Zest', category: 'Oils and Spices' },
  { name: 'Orange Juice', category: 'Beverages' },
  { name: 'Fruit Punch', category: 'Beverages' },
  { name: 'Sparkling Lemonade', category: 'Beverages' },
  { name: 'Energy Drink', category: 'Beverages' },
  { name: 'Milkshake', category: 'Beverages' },
  { name: 'Iced Tea', category: 'Beverages' },
];


export type Product = {
  name: string;
  category: string;
};

export const categories = [
  { id: 1, name: 'Basic Foods' },
  { id: 2, name: 'Oils and Spices' },
  { id: 3, name: 'Bakery' },
  { id: 4, name: 'Dairy' },
  { id: 5, name: 'Snacks' },
  { id: 6, name: 'Beverages' },
  { id: 7, name: 'Meats' },
  { id: 8, name: 'Fruits and Vegetables' },
  { id: 9, name: 'Hygiene' },
];
